name: Nightwatch E2E Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]
        browser: [chrome]
        include:
          # Add Firefox only on Ubuntu with Node 20
          - os: ubuntu-latest
            node-version: 20.x
            browser: firefox
          # Add one macOS test with Chrome
          - os: macos-latest
            node-version: 20.x
            browser: chrome

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Chrome
      if: matrix.browser == 'chrome'
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup Firefox
      if: matrix.browser == 'firefox'
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest

    - name: Run Nightwatch tests
      run: |
        if [ "${{ matrix.browser }}" = "chrome" ]; then
          npm run test:chrome
        else
          npm run test:firefox
        fi
      shell: bash
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-node${{ matrix.node-version }}-${{ matrix.browser }}
        path: tests_output/
        retention-days: 30

    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failure-screenshots-${{ matrix.os }}-node${{ matrix.node-version }}-${{ matrix.browser }}
        path: tests_output/screenshots/
        retention-days: 30